name: Release Tools
run-name: 'release tools ${{ github.ref }}'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install nodejs package
        run: yarn install

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install change log tools
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Generate change log
        run: |
          tag=$(git tag --list --sort -version:refname | head -n 1)
          git-chglog $tag > releaselog.md

      - name: Publish package
        run: yarn publish

      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: releaselog.md
          draft: false
          prerelease: false
